### ISSUE TITLE
Conflicting - or at least confusing - requirements.txt files

### ISSUE THREAD

**Issue by dave-xnor** [stackb/rules_proto#112]
`python/requirements.txt` specifies:

- `grpcio==1.20.0`
- `protobuf==3.7.1`

`python/requirements/grpc.txt` specifies:

- `grpcio==1.15.0`

`python/requirements/protobuf.txt` specifies:

- `protobuf==3.6.1`

So:

1. What are these different files used for?
1. Is it a problem that they don't name the same versions?
1. What is the relationship between the `grpcio` version named here and the one named in my own repos' `WORKSPACE`?
1. What is the relationship between the `protobuf` version named here and the one named in my own repos' `WORKSPACE`?  (I.e., which runtime is used, and which `protoc` is used?)
    - I actually don't have any `protobuf` repository named in my `WORKSPACE` though I do have `grpc` and `grpcio` repositories, so:
      1. Where is my `protobuf` coming from (grpc? rules_proto? bazel itself?)
      1. How do I find the versions of the `protobuf` (as well as `grpc`, `grpcio`) used by my code?

(I was unable to find answers to these questions in docs here, or in Bazel's docs - so a possible resolution of this issue might include updating docs somewhere...I'm sure I'm not the only one with questions like this (or at least I hope it's not just me ...))

**Comment by pshields** [comment]
I noticed this issue is still present. Also, the grcpio versions have not been updated in a while.

I'm actually running into an issue where the pinned grcpio version (1.20.0) is so old that it doesn't include a fix that I need that I believe shows up in >= 1.26.0. I'll probably look into patching requirements.txt locally to point to a more recent version of grpcio, to see if that fixes my issue.

**Comment by pcj** [comment]
Closing stale PRs and issue, please reopen new one if desired.
