### ISSUE TITLE
HTTPS required after Jan 15, 2020 for maven repo url.

### ISSUE THREAD

**Issue by anazri** [stackb/rules_proto#136]
As reportted here. https://support.sonatype.com/hc/en-us/articles/360041287334

**Comment by Offtree** [comment]
Is there any way around this for now?

**Comment by gertvdijk** [comment]
Should be fixed by https://github.com/stackb/rules_proto/commit/bedc40cd47b43dde857a7720066aadcf76c7dd3b, but keep in mind that transitive dependencies still pull in deps over http. If you're overriding the deps in your own WORKSPACE, you're fine, though. I'm using rules_proto here without issues, builds with clean Bazel cache: https://github.com/TulipSolutions/tecl/blob/dd5ada80495ce1680cdf109ca1284743f2a166d7/bazel/repositories.bzl#L171-L183

**Comment by pcj** [comment]
Closing stale PRs and issues, please reopen new one if desired.
