### ISSUE TITLE
What are the minimal dependencies to generate files in specific language? 

### ISSUE THREAD

**Issue by duyixian1234** [stackb/rules_proto#34]
I'm new to bazel, so this project is a little hard to me.Now I want generate python files for some proto files in this structure of python package, what should I do?
```
app\
  __init__.py
  wsgi.py
  protos\
    greeter.proto
    deps.proto
  grpc\
    # the python stub files.
```

**Comment by borg286** [comment]
Here is a github query of projects that pull in rules_proto
https://github.com/search?q=build_stack_rules_proto&type=Code
Randomly picking one that pulls in the python stuff
https://github.com/cbentzel/token
I'm neither the author of this repo nor the cbentzel one but someone that is also using stackb's repo.

**Comment by pcj** [comment]
It depends a bit on how much you want to "bazelify" your application / build workflow.
If you're just looking for a way to download the necessary plugins & generate the proto artifacts you may not need bazel (or this repository) at all, just follow directions in https://grpc.io/docs/tutorials/basic/python.html.

If you'd like to automate building the plugin(s) and generating the artifacts (using bazel), this is what your `WORKSPACE` would look like:

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_stack_rules_proto",
    urls = ["https://github.com/stackb/rules_proto/archive/d86ca6bc56b1589677ec59abfa0bed784d6b7767.tar.gz"],
    sha256 = "36f11f56f6eb48a81eb6850f4fb6c3b4680e3fc2d3ceb9240430e28d32c47009",
    strip_prefix = "rules_proto-d86ca6bc56b1589677ec59abfa0bed784d6b7767",
)

load("@build_stack_rules_proto//python:deps.bzl", "python_grpc_compile")

python_grpc_compile()
```

At this point, you should create a `protos/BUILD.bazel` file and add:

```python
proto_library(
    name = "greeter_proto",
    srcs = ["greeter.proto"],
    deps = [":deps_proto"],
)

proto_library(
    name = "deps_proto",
    srcs = ["deps.proto"],
)
```

(assuming greeter imports something from `deps.proto`).

At this point, make sure you can build the proto_library targets:

```sh
$ bazel build //protos:deps_proto 
$ bazel build //protos:greeter_proto
```

The outputs of those rules are the descriptor set(s).  Hopefully, so far so good.  

Next, prove you can at least generate the python artifacts. :

```python
# Also in protos/BUILD.bazel
load("@build_stack_rules_proto//python:python_grpc_compile.bzl", "python_grpc_compile")

python_grpc_compile(
    name = "greeter_python_grpc",
    deps = [":greeter_proto"],
)
``` 

And build it:

```sh
$ bazel build //protos:greeter_python_grpc
```

With luck, everything will be generated successfully and you'll have `./bazel-genfiles/protos/greeter_pb2.py`, `./bazel-genfiles/protos/greeter_pb2_grpc.py`, `./bazel-genfiles/protos/deps_pb2.py`, `./bazel-genfiles/protos/deps_pb2_grpc.py`.

At this point, you'll need to decide if you want to build and package your application (and runtime dependencies) with bazel or stick with a more traditional python workflow.  

My recommendation would be to remain with what you are comfortable with for now.  If you decide to go the "all-bazel" route, it could be days/weeks of learning (which is interesting) but will slow you down in terms of finishing the actual application you're trying to create.

In that case, you might decide to write a shell script that copies the generated artifacts out of `bazel-bin` and into whatever directory you want the source files to be in, and find/replace | sed the import statements to match.

If you choose this route, you'll need to add the requirements like https://github.com/stackb/rules_proto/blob/master/python/requirements.txt so that the runtime dependencies will be available in your environment.

If you choose the "all-bazel" route, follow the example in https://github.com/stackb/rules_proto/tree/master/python/example/python_grpc_library and update this thread with your progress.

**Comment by duyixian1234** [comment]
@borg286 @pcj Thank you guys and I've solved the problem.
