### ISSUE TITLE
Gazelle like generator

### ISSUE THREAD

**Issue by clanstyles** [stackb/rules_proto#40]
Is there anyway to generate the build files like we can with gazelle?

**Comment by pcj** [comment]
Meaning, given a repository with proto files, automatically generate BUILD.bazel files for them?  I have written such a tool but have not open-sourced it ATM, still pretty rough.

**Comment by clanstyles** [comment]
Yeah. Basically Gazelle does this for the Go code, you just have to go in and tweak it.

Right now I'm writing some build files for a bunch of ours and it's just taking forever. Most of it is boilerplate.

**Comment by clanstyles** [comment]
Gazelle actually deletes the `go_library` you build to reference the `go_proto_library`.

**Comment by peter-edge** [comment]
I'm writing such a tool as well FYI, but also not exposed.

**Comment by peter-edge** [comment]
A little update here: I have this up on a branch, but I think I/we should abandon this in favor leaning into Gazelle.

Long:

Here's an examplle of what I have right now:

https://github.com/uber/prototool/blob/bazel-generate/Makefile#L77
https://github.com/uber/prototool/blob/bazel-generate/example/proto/prototool.yaml#L21
https://github.com/uber/prototool/blob/bazel-generate/example/proto/uber/foo/v1/BUILD.bazel

This was fun to build, however after doing so, I looked more into Gazelle and they just (in the last two months or so) released [Language extensions](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.rst). There is definitely some help we could provide in making this a bit more abstract if the Gazelle maintainers were open to it, but I think it would be preferable if there were a single Bazel rule generation framework that was extensible (IMO, extensible, configurable Bazel rule generation is the missing killer Bazel tool). Instead of us all building our own tooling, it'd be nice to centralize the effort so everyone isn't reinventing the wheel (for example, `prototool bazel generate` is just an extremely simplistic framework relative to Gazelle for Bazel rules)

I filed https://github.com/bazelbuild/bazel-gazelle/issues/452 but as I mention there, I think stackb rules would be better done separately. We could have `Language` implementation in stackb for Gazelle. An example of an existing one is at https://github.com/achew22/rules_sass Internally, I've found this relatively easy to set up, although it would be nice if there were some plugin mechanism (think protoc, but 2019 edition without some of the cruft) that didn't require building a new binary, or alternatively Gazelle was an abstract Golang library that allowed easy creation of independent binaries.

**Comment by alexeagle** [comment]
FWIW I know @pcj has written a Gazelle plugin for generating these rules at one client, I think we could open-source

**Comment by pcj** [comment]
Wow, old issue, this is now implemented on master.
