### ISSUE TITLE
Documentation needs to clarify relationship between various rules.

### ISSUE THREAD

**Issue by michaelsafyan** [stackb/rules_proto#8]
The documentation does not sufficiently clarify the difference betwen 'artifact' and 'library'. It also does not sufficiently clarify the relationship between the 'compile' and 'library' rules. 

The documentation should, for example, clarify whether the 'deps' and/or 'srcs' of the '_library' rules are intended to be the output of the '_compile' rules or whether the 'deps'/'srcs' of the '_library' rules are intended to be the same as that of the '_compile' rules. That is, it is unclear from the documentation whether the 'compile' and 'library' rules represent separate build steps that are intended to be chained together, or whether one is a superset of the other.

Likewise, the documentation fails to clarify the relationship between these rules and that of the native 'proto_library' rule; for example, can the output of a 'proto_library' be specified as an input to either of these rules? Or are these rules always going to duplicate the 'proto_library' step?

**Comment by pcj** [comment]
Point taken.  I've tried to take the approach to generate an example `WORKSPACE` and `BUILD.bazel` file that demonstrates a functioning / buildable example.  However, documentation on the individual rule attributes needs some attention.

Here's the basic idea: 

1. Always start with a native `proto_library` rule.
2. If you only want to the generated source code artifacts, use a `{lang}_proto_compile` rule.  `deps` always point to `proto_library` rules.
3. If you want the code artifacts "compiled" or incorporated into some `{lang}_library` rule, use the `{lang}_proto_library` rules.  `deps` also point to `proto_library` rules.  For this class of rules, there *should be* an escape hatch to provide additional language-specific deps if necessary, like for example `py_deps` that would be passed to the `py_library.deps` attribute.  This convention is currently lacking but it usually not necessary since most people keep their proto rules independent of their application specific code.
4. If your proto has services, use a `{lang}_grpc_{compile|library}` rule instead.

**Comment by pcj** [comment]
Should be addressed by #9.  Feedback welcome.
